name: CMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configure cmake
      run: cmake -S . -B build -DENABLE_SANITIZER_ADDRESS=ON -DENABLE_SANITIZER_UNDEFINED=ON

    - name: Build
      run: cmake --build build

    - name: Run Engine Sanity Check
      run: ./build/engine

    - name: Run Unit Tests with Sanitizers
      run: ./build/tests/engine_tests