name: CMake CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Clean Build Cache
      run: make clean

    - name: Run Engine Sanity Check
      run: make run

    - name: Run Standard Unit Tests
      run: |
        make clean
        make test

    - name: Test with ASan and UBSan
      run: |
        make clean
        make test-asan

    - name: Test with TSan
      run: |
        make clean
        make test-tsan